#ifndef HEAL_H
#define HEAL_H

//------------------------------------------------------------------------------
// Away-level healing: droids on inactive levels don't simulate, but when the player
// returns their health is regenerated by how long they were left (a single pass, at
// re-entry). Pure + header-only so it is unit-testable without a GL/physics context.
// See docs/levels.md.
//------------------------------------------------------------------------------

// Fraction of max health regenerated per second the level was inactive (~full in 50s).
inline constexpr float AWAY_HEAL_FRACTION_PER_SEC = 0.02f;

// current health healed by `secondsAway` at `fracPerSec` of maxHealth, clamped to
// [0, maxHealth]. Negative time and zero max are handled safely.
inline float away_healed_health(float current, float maxHealth, double secondsAway,
                                float fracPerSec) {
    if (maxHealth <= 0.0f) return current;
    double away = secondsAway > 0.0 ? secondsAway : 0.0;
    double healed = static_cast<double>(current) +
                    static_cast<double>(maxHealth) * static_cast<double>(fracPerSec) * away;
    if (healed > maxHealth) healed = maxHealth;
    if (healed < 0.0) healed = 0.0;
    return static_cast<float>(healed);
}

#endif // HEAL_H
